# Generated by Django 5.0 on 2024-02-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_students_password_students_username'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_set', related_query_name='student', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='students',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='students',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_set', related_query_name='student', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
